Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'rnn_hls4ml/hls4ml_prj/keras_model.keras'
OutputDir: rnn_hls4ml/hls4ml_prj
OutputPredictions: null
Part: xcku115-flvb2104-2-i
ProjectName: myproject
Stamp: 52cDa60b
Version: 1.0.0
